name: CI

on:
  push:
    branches: ["**"]          # run on any branch push
    paths: 
      - "client/**"
      - "./github/workflows/ci.yml"
  pull_request:
    branches: [main]   # and on PRs into main
    paths:       
      - "client/**"
      - "./github/workflows/ci.yml"
  workflow_dispatch:          # manual "Run workflow" button

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install deps 
        run: npm ci 

      - name: Build 
        run: npm run 
