name: CI
on:
  pull_request:
    branches: [ main, develop ]
jobs:
  build:
    runs-on: ubuntu-lates
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npm run build -w shared
      - run: npm run build -w api
      - run: npm run build -w client
